# Generated by Django 2.0.7 on 2018-12-05 08:16

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitoutput',
            name='output',
            field=models.FileField(upload_to=judge.models.user_output_directory_upload),
        ),
    ]
