# Generated by Django 2.0.7 on 2018-12-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20181205_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='judge.Campus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Campus'),
        ),
    ]
