# Generated by Django 2.0.7 on 2018-12-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20181205_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('active_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('frozen_time', models.DateTimeField(blank=True, null=True)),
                ('unfrozen_time', models.DateTimeField(blank=True, null=True)),
                ('deactivate_time', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='icpc.png', upload_to='')),
                ('register_date', models.DateTimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Campus')),
                ('problem', models.ManyToManyField(to='judge.Problem')),
                ('user', models.ManyToManyField(to='judge.User')),
            ],
        ),
    ]
