# Generated by Django 2.0.7 on 2018-12-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enable',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=200),
        ),
    ]
